### ISSUE TITLE
EDM object TextupdateClass units not displayed

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/wedm#33]
Given a an EDL file containing:

```
# (Text Update)
object TextupdateClass
beginObjectProperties
major 10
minor 0
release 0
x 273
y 457
w 113
h 29
controlPv "REDACTED"
fgColor index 14
bgColor index 70
font "helvetica-bold-r-16.0"
fontAlign "right"
endObjectProperties
```

The expected widget display should include units.  This may depend on the "Mode" attribute, which by default (missing) apparently means show units:

<img width="202" alt="thumbnail_Screenshot from 2024-02-28 14-26-33" src="https://github.com/JeffersonLab/wedm/assets/2642119/9dedf6a5-ef29-4fa1-8d9a-1c221cc9f4d1">

Reported by Brad Webb (ORNL).   

**Note**: WEDM does support units on the EDM object activeXTextDspClass, [Example]( https://github.com/JeffersonLab/wedm/wiki/WEDM-Objects#text-control).  That works differently apparently though:

1. EDL file contains [showUnits](https://github.com/JeffersonLab/wedm/blob/38a08988837ab073dc7280a3a7deae447a0b1488/examples/edl/wedm/objects/TextControl.edl#L325)
1. Server-side widget parser marks the output HTML with flag [data-show-units](https://github.com/JeffersonLab/wedm/blob/38a08988837ab073dc7280a3a7deae447a0b1488/src/main/java/org/jlab/wedm/widget/html/ActiveControlText.java#L27-L29)
1. Client-side browser code looks for [flag](https://github.com/JeffersonLab/wedm/blob/38a08988837ab073dc7280a3a7deae447a0b1488/src/main/webapp/resources/js/screen.js#L625)
1. Then knows to register for [.EGU](https://github.com/JeffersonLab/wedm/blob/38a08988837ab073dc7280a3a7deae447a0b1488/src/main/webapp/resources/js/screen.js#L657-L660)
1. Then sets .EGU updates to HTML [data-units](https://github.com/JeffersonLab/wedm/blob/38a08988837ab073dc7280a3a7deae447a0b1488/src/main/webapp/resources/js/screen.js#L252-L253)
1. Then  widget client-side code [handles](https://github.com/JeffersonLab/wedm/blob/38a08988837ab073dc7280a3a7deae447a0b1488/src/main/webapp/resources/widgets/activeXTextDspClass/widget.js#L81-L83)

**Comment by sbwebb** [comment]
What I observe is this:
When the Mode field is default, the widget always displays units. And the "displayMode" property is absent from the widget definition as seen above.

When you change the Mode field to any of the other available options other than "default" the units are not displayed in the widget. And the "displayMode" property and its value are present in the widget definition

# (Text Update)
object TextupdateClass
beginObjectProperties
major 10
minor 0
release 0
x 273
y 457
w 113
h 29
controlPv "REDACTED"
displayMode "decimal"
fgColor index 14
bgColor index 70
font "helvetica-bold-r-16.0"
fontAlign "right"
endObjectProperties


![Screenshot from 2024-02-29 07-46-49](https://github.com/JeffersonLab/wedm/assets/6588415/072284f0-201b-4f39-91ac-362f83f31a39)
![Screenshot from 2024-02-29 07-47-21](https://github.com/JeffersonLab/wedm/assets/6588415/795befdb-c9ce-4770-aff9-3654d39a3a22)
