### ISSUE TITLE
CAMAC Status Summary Alarm isn't triggering as expected

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/wedm#38]
**Problem**:

The CAMAC status screen is indicating that iocctf crate-1 and crate-2, and iocch2a crate-18 are in alarm in EDM, but not in WEDM.

**EDM**
![thumbnail_Screenshot from 2024-04-03 10-41-40](https://github.com/JeffersonLab/wedm/assets/2642119/7264a644-c71b-45e9-aced-1a39f442a7d2)

**WEDM**
![thumbnail_epicsweb](https://github.com/JeffersonLab/wedm/assets/2642119/7fdc4753-4ec3-48ac-976b-d65bc4a95d57)

[WEDM Link to Screen](https://epicsweb.jlab.org/wedm/screen?edl=/cs/opshome/edm/wedm/otf-pregen/T1RGTGF1bmNoZXIgaW9jIGNhbWFjc3VtbWFyeQ==.edl)

**Triage**:
Alarm PV CALC expressions:

crate-18
```
CALC\\{max(A,B,C,D,E,F,G,H)}(analog_Temp_ch2a_18.STAT,analog_P24v_ch2a_18.STAT,analog_P12v_ch2a_18.STAT,analog_P6v_ch2a_18.STAT,analog_Ground_ch2a_18.STAT,analog_N6v_ch2a_18.STAT,analog_N12v_ch2a_18.STAT,analog_N24v_ch2a_18.STAT)
```

crate-1
```
CALC\\{max(A,B,C,D,E,F,G,H)}(analog_Temp_ctf_1.STAT,analog_P24v_ctf_1.STAT,analog_P12v_ctf_1.STAT,analog_P6v_ctf_1.STAT,analog_Ground_ctf_1.STAT,analog_N6v_ctf_1.STAT,analog_N12v_ctf_1.STAT,analog_N24v_ctf_1.STAT)
```

crate-2
```
CALC\\{max(A,B,C,D,E,F,G,H)}(analog_Temp_ctf_2.STAT,analog_P24v_ctf_2.STAT,analog_P12v_ctf_2.STAT,analog_P6v_ctf_2.STAT,analog_Ground_ctf_2.STAT,analog_N6v_ctf_2.STAT,analog_N12v_ctf_2.STAT,analog_N24v_ctf_2.STAT)
```

**Reported by**:

Joseph Sawyer

**Comment by slominskir** [comment]
I noticed the values of the STAT fields appear to be interpreted as Strings, and these may be fed into the JavaScript Math.max() function, which probably doesn't do what we want to a string.  The PV type is DBR_ENUM, so we want the index into the enum array presumably.   Will need to investigate further.

For example:
caget of [analog_Temp_ch2a_18.STAT](https://epicsweb.jlab.org/epics2web/caget?pv=analog_Temp_ch2a_18.STAT) =
```
{"data":[{"name":"analog_Temp_ch2a_18.STAT","value":"NO_ALARM"}]}
```

**Comment by slominskir** [comment]
There is something odd with the CALC expressions.  The screen in question is actually an on-the-fly screen so a cached version is created for WEDM here:

```
/cs/opshome/edm/wedm/otf-pregen/T1RGTGF1bmNoZXIgaW9jIGNhbWFjc3VtbWFyeQ==.edl
```

This means the EDL seen in EDM launched from JMenu may differ from the EDL seen by WEDM.

When you run this cached version of the screen with EDM you see:

```
CALC '{max(A,B,C,D,E,F,G,H)}': error in expression 'max(A,B,C,D,E,F,G,H)'
```

Using crate-18 as an example, the widget EDL looks like:

```
# (Rectangle)
object activeRectangleClass
beginObjectProperties
major 4
minor 1
release 0
x 677
y 528
w 15
h 10
lineColor index  14
lineWidth  1
fill
fillColor index 113
alarmPv  CALC\\\{max(A,B,C,D,E,F,G,H)\}(analog_Temp_ch2a_18.STAT,analog_P24v_ch2a_18.STAT,analog_P12v_ch2a_18.STAT,analog_P6v_ch2a_18.STAT,analog_Ground_ch2a_18.STAT,analog_N6v_ch2a_18.STAT,analog_N12v_ch2a_18.STAT,analog_N24v_ch2a_18.STAT)
fillAlarm
endObjectProperties
```

**Comment by slominskir** [comment]
I created a test EDL file for this issue containing just crate-18 and debug of each piece of the expression at 
`/cs/opshome/edm/wedm/tests/calc-alarm.edl` and it looks like:
![image](https://github.com/JeffersonLab/wedm/assets/2642119/17d030cb-11f1-4409-ab7f-dbafb1c42d5d)

**Comment by theojlab** [comment]
The cached edl should be exactly what EDM runs.

When OTFLauncher  executes, tools writes an EDL file to a temp directory, invokes EDM, and then deletes the temp file.  The caching process merely preserves that temp file.



From: Ryan Slominski ***@***.***>
Sent: Thursday, April 4, 2024 11:44 AM
To: JeffersonLab/wedm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [JeffersonLab/wedm] CAMAC Status Summary Alarm isn't triggering as expected (Issue #38)


There is something odd with the CALC expressions. The screen in question is actually an on-the-fly screen so a cached version is created for WEDM here:

/cs/opshome/edm/wedm/otf-pregen/T1RGTGF1bmNoZXIgaW9jIGNhbWFjc3VtbWFyeQ==.edl

This means the EDL seen in EDM launched from JMenu may differ from the EDL seen by WEDM.

When you run this cached version of the screen with EDM you see:

CALC '{max(A,B,C,D,E,F,G,H)}': error in expression 'max(A,B,C,D,E,F,G,H)'

Using crate-18 as an example, the widget EDL looks like:

# (Rectangle)

object activeRectangleClass

beginObjectProperties

major 4

minor 1

release 0

x 677

y 528

w 15

h 10

lineColor index  14

lineWidth  1

fill

fillColor index 113

alarmPv  CALC\\\{max(A,B,C,D,E,F,G,H)\}(analog_Temp_ch2a_18.STAT,analog_P24v_ch2a_18.STAT,analog_P12v_ch2a_18.STAT,analog_P6v_ch2a_18.STAT,analog_Ground_ch2a_18.STAT,analog_N6v_ch2a_18.STAT,analog_N12v_ch2a_18.STAT,analog_N24v_ch2a_18.STAT)

fillAlarm

endObjectProperties

**Comment by slominskir** [comment]
Digging deeper and trying to find the code that handles CALC expressions inside an alarm PV revealed a simpler explanation: there isn't any CALC handling in the rectangle widget [handleAlarmUpdate](https://github.com/JeffersonLab/wedm/blob/11de469afa833bc53534c8261ac303712a689072/src/main/webapp/resources/widgets/activeRectangleClass/widget.js#L31) function in WEDM at the moment.  Further, the way normal (non-CALC) alarms work in WEDM is the provided PV has the `.SEVR` field appended and monitored.    In this particular case not only is there a CALC expression, but the values inside are not top level PV names, but specific fields, and specifically the `.STAT` field.   This is interesting because EDM Color rules don't appear to have any support for anything other than values 0-3, which aligns with the `.SEVER` field alarm colors.  The `.STAT` field can have dozens of different values so if not careful the max() of various `.STAT` fields will map to `invalid alarm color` if using the `.SEVR`  alarm value-to-color logic.  

https://github.com/JeffersonLab/wedm/blob/11de469afa833bc53534c8261ac303712a689072/examples/edl/colors.list#L130-L136

**Comment by slominskir** [comment]
There is no specification for EDM, so WEDM is simply reverse engineered from observing what EDM does.  So I need to figure out how this is supposed to work.

If I recall correctly there is no reason to have different sets of color rules for alarms as that would be confusing if all screens didn't follow the same green = no alarm, yellow = minor, red = major color rule.   So my understanding is if you set the "fillAlarm" attribute then that means ignore the colorRule index (`fillColor index 113
` in our case) and use the one global alarm color rule instead. 

As an aside, the 113 color rule corresponds to: 

https://github.com/JeffersonLab/wedm/blob/11de469afa833bc53534c8261ac303712a689072/examples/edl/colors.list#L263-L270

And if we weren't ignoring it then it would also suffer from marking anything greater than 4 as invalid if the `.STAT` field was used.

So it appears the logic should be strip off any extraneous field specifiers on each PV in the CALC expression and force `.SEVR` monitoring instead.

If the "alarm sensitive" field was unchecked then "fillAlarm" would no longer show up in the EDL file, and the "alarmPv" attribute would be replaced with "colorPv" instead.  Note: The rectangle widget [handleColorUpdate](https://github.com/JeffersonLab/wedm/blob/11de469afa833bc53534c8261ac303712a689072/src/main/webapp/resources/widgets/activeRectangleClass/widget.js#L81) function already does support CALC expressions.


I think the dynamically generated screen generator might be appending a `.STAT` field to each PV unnecessarily, but I might be missing something.
