### ISSUE TITLE
Pulling up a related display has wrong path

### ISSUE THREAD

**Issue by gmilanov** [JeffersonLab/wedm#5]
Ryan et al,

Amazing job! I can't believe how well this works out of the box. Our colors.list file doesn't quite work with your parsing, but that's probably something we should fix locally.

One issue: when clicking on a related display that opens in a new window, the wrong path is appended to the URL.
Instead of pulling up /wedm/screen/...
it pulls up /wedm/undefined/wedm/screen/...

I think the problem may lie in line 52 of wedm/web/resources/widgets/relatedDisplayClass/widget.js

where it tries to append jlab.conxtextprefix and the path again. 

Note that embedded screens do work perfectly. 

Not sure if this is unintended behavior, or we need to define jlab.contextprefix ENV, or it is something also to be changed on a separate branch for SNS if we pursue this further. I don't want to break your stuff!

Thanks,
Geoff

**Comment by slominskir** [comment]
Thanks for reporting these issues.  Please send me your colors.list file and I'll troubleshoot that issue.   As far as the related display path issue that is probably a bug - I'll take a look.  In the meantime the workaround is likely to set the environment variable CONTEXT_PREFIX to an empty string (it should default to an empty string if not defined, but apparently it isn't).

**Comment by slominskir** [comment]
I'm having trouble reproducing the CONTEXT_PREFIX undefined issue.  What OS are you using?  What web browser make and model?  I ran the generated HTML through an HTML validator and it found some errors so at this point my best theory is some browsers don't like the imperfect HTML (w3.org says there are unclosed tags).  I'll clean it up and maybe that will fix it.

**Comment by gmilanov** [comment]
I defined CONTEXT_PREFIX to an empty string and it still adds the extra
directory structure.  OS X 10.11.6, Mozilla Firefox 57.0.2.

**Comment by slominskir** [comment]
Figured it out.  I forgot to create the release bundle for v1.0.1.   Version 1.0.0 has the regression that breaks Related Display.  I committed the code nearly a month ago and got side tracked.   I've packaged up the bugfix release v1.0.1.  I'll close this and create a new issue for the colors.list file.

**Comment by slominskir** [comment]
New ORNL colors.list file issue: https://github.com/JeffersonLab/wedm/issues/6
